---
# This is purely informative
# This would be the resulting output of the ansible/roles/argo template
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-short-name-services
  namespace: argocd
  labels:
    k8s-app: app-of-apps
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-services
    repoURL: git@github.com:matoszz/blog.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-cluster-short-name.yaml
