---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: external-dns
  namespace: external-dns
spec:
  selector:
    matchLabels:
      k8s-app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.7.1
        args:
          - --source=service
          - --source=ingress
          - --domain-filter={{ .Values.clusterFQDN }}
          {{- range .Values.additionalDomains }}
          - --domain-filter={{ . }}
          {{- end }}
          - --registry=txt
          - --txt-owner-id={{ .Values.clusterFQDN }}
          {{- if eq .Values.dnsProvider "route53" }}
          - --provider=aws
          - --aws-zone-type=public
          {{- else if eq .Values.dnsProvider "ns1" }}
          - --provider=ns1
          {{- end }}
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 500Mi
